### ISSUE TITLE
Application crashes if the data connectivity is on but there is no data left or there is no connectivity

### ISSUE THREAD

**Issue by Pritom14** [dharan1011/Popular-Movie-App#18]
For instance, if you have 1GB limit per day on your data pack and if suppose the 1GB is over on a certain day then the application will crash even if you keep the data connection on.

**Comment by Pritom14** [comment]
Fix #14

**Comment by dharanad** [comment]
Thanks

**Comment by Pritom14** [comment]
You're welcome.

On 16-Oct-2017 3:14 PM, "Dharan Aditya" <notifications@github.com> wrote:

Thanks

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/dharan1011/Popular-Movies/issues/18#issuecomment-336835731>,
or mute the thread

**Comment by dharanad** [comment]
Fixed
