### ISSUE TITLE
Migrate from Local Database & Implement Authentication

### ISSUE THREAD

**Issue by dharanad** [dharan1011/Popular-Movie-App#9]
Migrate from local SQLite database to firebase and protect the user data by implementing phone number authentication. This way the user favourite movies in will in sync in all the devices.

**Comment by chizoba** [comment]
i can work on the phone number authentication. should i go ahead?

**Comment by dharanad** [comment]
@chizoba create a new branch and make changes in it. Go Ahead.

**Comment by rajtheinnovator** [comment]
@dharan1011  I think this issue can be closed now, hopefully :)
